spring.application.name=auth-service

# ==========================================
# SERVER
# ==========================================

server.port=8081


# ==========================================
# POSTGRESQL
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/integrityai_auth

spring.datasource.username=postgres

spring.datasource.password=root


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=health,info


# ==========================================
# SWAGGER
# ==========================================

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui.html