spring.application.name=submission-service
server.port=8083

spring.data.mongodb.uri=mongodb+srv://USERNAME:PASSWORD@CLUSTER.mongodb.net/integrityai_submission
spring.data.mongodb.database=integrityai_submission